CREATE DATABASE haebeop;
USE haebeop;

CREATE TABLE test(
	num INT AUTO_INCREMENT PRIMARY key,
	title VARCHAR(200));
	
INSERT INTO test VALUES (DEFAULT, '테스트제목1');
INSERT INTO test VALUES (DEFAULT, '테스트제목2');
INSERT INTO test VALUES (DEFAULT, '테스트제목3');
INSERT INTO test VALUES (DEFAULT, '테스트제목4');
INSERT INTO test VALUES (DEFAULT, '테스트제목5');

DESC test;

SELECT * FROM emp;

CREATE TABLE USER(
	id VARCHAR(20) PRIMARY KEY,
	pw VARCHAR(350) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	tel VARCHAR(20),
	addr1 VARCHAR(200),
	addr2 VARCHAR(200),
	postcode VARCHAR(20),
	regdate DATETIME DEFAULT CURRENT_TIME,
	birth DATE DEFAULT CURRENT_date,
	pt INT DEFAULT 0,
	visited INT DEFAULT 0);
	
	
INSERT INTO USER VALUES('admin','1234','관리자','admin@edu.com',DEFAULT, DEFAULT, DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO USER VALUES('kimbk','1234','김보경','kimbk@edu.com',DEFAULT, DEFAULT, DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT);

SELECT * FROM user;

DROP TABLE user;
